#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine

# Get all active IPv4 addresses
ip_addresses=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Display the IP addresses
for ip in $ip_addresses; do
    echo $ip
done
